# -*- coding: utf-8 -*-
"""beecrowd1011_volume_da_esfera.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XA5G_B7jARP-AvuFWiSaWaMpDV2UrvJe

#  Problema: Volume da Esfera

**Descrição:**  
Calcular o volume de uma esfera dado o valor do raio **R**.

**Fórmula matemática:**

$$
V = \frac{4}{3} \cdot \pi \cdot R^3
$$



---

##  Entrada
- Um número real representando o raio da esfera.

##  Saída
- O volume da esfera com **3 casas decimais**, no formato:
"""

raio = float(input())

pi = 3.14159

v = (4/3) * pi * (raio ** 3)

print(f"VOLUME = {v:.3f}")